---
name: Test PyEasyArchive

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install apt dependencies
        run: |
          sudo apt-get install -y libarchive-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run nose2 tests
        run: |
          python -m nose2 -v --log-capture
